#!/bin/bash

#Print applicable error messages from Github server
function showErrors {
python <<END_OF_PYTHON
import json  
response = json.load(open('.jsongit'))

print response['message']
if 'errors' in response:
  for error in response['errors']:
    if 'message' in error: print error['message']
END_OF_PYTHON
}

#Create a JSON object and retrieve 'clone_url' value
function geturl {

python <<END_OF_PYTHON  
import json
repo = json.load(open('.jsongit'))
print repo['ssh_url']
END_OF_PYTHON

}

auth="swanyriver"
json="{\"name\":\"$1\", \"description\":\"$2\"}"
url="https://api.github.com/user/repos"

#Capture HTTP response code and send JSON data to file
htresp=$(curl --write-out %{http_code} --output .jsongit -u "$auth" $url -d "$json" )

if [[ $htresp == 201 ]] ; then
  #Succsefully created a remote repository
  echo "created github repo: $1"
  
  #Get remote repository URL
  cloneurl=$(geturl)
  rm .jsongit
  
  #Set up Local repository for Push/Pull
  git init
  git add -A :/
  git commit -m "first commit"
  git remote add origin $cloneurl
  git push -u origin master
  exit 0
else
  #display error message, exit in failure
  echo "FAILED: github response code $htresp"
  showErrors
  rm .jsongit
  exit 1
fi

