#!/bin/bash
function allos {
    pattern=""
    while (( $# )); do
        pattern="$pattern$1|"
        shift
    done
    echo "pattern was:$pattern";
    \grep --color=always -i -E -A5 -B5 ${pattern::-1} $text | less -R
}

text=$1

while (( 1 )); do
    echo -n "search $text\$ "
    read searches
    if [[ ! -z searchers ]] ; then 
        allos ${searches}
    fi    
done
    

#allos $@         
