" Generated by vim-plug
" Fri 19 Apr 2024 05:42:24 PM PDT
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim
" compatible with NVIM v0.9.5 07/25/2024

silent! let g:plugs['Comment.nvim'].commit = 'e30b7f2008e52442154b66f7c519bfd2f1e32acb'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-nvim-lsp'].commit = '39e2eda76828d88b773cc27a3f61d2ad782c922d'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['fzy-lua-native'].commit = '820f745b7c442176bcc243e8f38ef4b985febfaf'
silent! let g:plugs['indent-blankline.nvim'].commit = '9637670896b68805430e2f72cf5d16be5b97a22a'
silent! let g:plugs['nvim-cmp'].commit = 'd818fd0624205b34e14888358037fb6f5dc51234'
silent! let g:plugs['nvim-lspconfig'].commit = '9c762dcd457d2ab99edb3f3433cea9865ded47ad'
silent! let g:plugs['nvim-treesitter'].commit = '63be47f203d3e9174fdac3872fb9766e5bcc5a11'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '34867c69838078df7d6919b130c0541c0b400c47'
silent! let g:plugs['plenary.nvim'].commit = 'a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683'
silent! let g:plugs['pounce.nvim'].commit = 'dbcba680fa7921e8d13a273bdae43178bd9a1964'
silent! let g:plugs['targets.vim'].commit = '6325416da8f89992b005db3e4517aaef0242602e'
silent! let g:plugs['telescope-fzy-native.nvim'].commit = '282f069504515eec762ab6d6c89903377252bf5b'
silent! let g:plugs['telescope.nvim'].commit = '47ab113de540d1d1d9cdf7dba76dc60ddd808bb8'
silent! let g:plugs['vim-ReplaceWithRegister'].commit = 'aad1e8fa31cb4722f20fe40679caa56e25120032'
silent! let g:plugs['vim-airline'].commit = 'd25c049e617775eb2eb26c580e5dec591c94d480'
silent! let g:plugs['vim-commentary'].commit = 'c4b8f52cbb7142ec239494e5a2c4a512f92c4d07'
silent! let g:plugs['vim-signify'].commit = '8670143f9e12ed1cd3c9b2c54f345cdd9a4baac3'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-titlecase'].commit = '69a697c54a08ca5603cb757b4d4f78cd4b567549'
silent! let g:plugs['vim-vinegar'].commit = 'bb1bcddf43cfebe05eb565a84ab069b357d0b3d6'
silent! let g:plugs['vim-vsnip'].commit = '02a8e79295c9733434aab4e0e2b8c4b7cea9f3a9'

PlugUpdate!

