" Generated by vim-plug
" Fri 19 Apr 2024 05:42:24 PM PDT
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim
" compatible with NVIM v0.7.2

silent! let g:plugs['Comment.nvim'].commit = '0236521ea582747b58869cb72f70ccfa967d2e89'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'affe808a5c56b71630f17aa7c38e15c59fd648a8'
silent! let g:plugs['cmp-vsnip'].commit = '0abfa1860f5e095a07c477da940cfcb0d273b700'
silent! let g:plugs['fzy-lua-native'].commit = 'aa00feb01128c4d279c8471898e15898e75d5df5'
silent! let g:plugs['indent-blankline.nvim'].commit = '9637670896b68805430e2f72cf5d16be5b97a22a'
silent! let g:plugs['nvim-cmp'].commit = '706371f1300e7c0acb98b346f80dad2dd9b5f679'
silent! let g:plugs['nvim-lspconfig'].commit = 'da7461b596d70fa47b50bf3a7acfaef94c47727d'
silent! let g:plugs['nvim-treesitter'].commit = 'e7b5e92d46355919e96e78f596bd5297c9ef77dd'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '30a5e25f92852fa8ee57d49760f08e37f1f614ed'
silent! let g:plugs['plenary.nvim'].commit = '31807eef4ed574854b8a53ae40ea3292033a78ea'
silent! let g:plugs['pounce.nvim'].commit = 'dbcba680fa7921e8d13a273bdae43178bd9a1964'
silent! let g:plugs['targets.vim'].commit = '8d6ff2984cdfaebe5b7a6eee8f226a6dd1226f2d'
silent! let g:plugs['telescope-fzy-native.nvim'].commit = '7b3d2528102f858036627a68821ccf5fc1d78ce4'
silent! let g:plugs['telescope.nvim'].commit = '8746347ac4065f5795e7bd33c7912ab1152cca4b'
silent! let g:plugs['vim-ReplaceWithRegister'].commit = 'aad1e8fa31cb4722f20fe40679caa56e25120032'
silent! let g:plugs['vim-airline'].commit = '61042e35024a133bb5af42850d3852d20ebcc4e1'
silent! let g:plugs['vim-commentary'].commit = '3654775824337f466109f00eaf6759760f65be34'
silent! let g:plugs['vim-signify'].commit = '69498f6d49f3eeac06870012416dd9bf867b84f3'
silent! let g:plugs['vim-surround'].commit = 'bf3480dc9ae7bea34c78fbba4c65b4548b5b1fea'
silent! let g:plugs['vim-titlecase'].commit = '69a697c54a08ca5603cb757b4d4f78cd4b567549'
silent! let g:plugs['vim-vinegar'].commit = 'bb1bcddf43cfebe05eb565a84ab069b357d0b3d6'
silent! let g:plugs['vim-vsnip'].commit = '8f199ef690ed26dcbb8973d9a6760d1332449ac9'

PlugUpdate!

